# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  serialized_pb=b'\n\tapi.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\x04Line\x12\x0c\n\x04line\x18\x01 \x01(\t\x12\x0c\n\x04\x66ont\x18\x02 \x01(\x03\"*\n\nBlankLines\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x0c\n\x04\x66ont\x18\x02 \x01(\x03\":\n\x06QRCode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x12\n\npixel_size\x18\x02 \x01(\x03\x12\x0e\n\x06\x63\x65nter\x18\x03 \x01(\x08\"7\n\x07\x42\x61rcode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x65nter\x18\x02 \x01(\x08\x12\x0e\n\x06\x62lanks\x18\x03 \x01(\x05\x32\xd4\x01\n\x0cPrintService\x12.\n\x05Print\x12\x0b.proto.Line\x1a\x16.google.protobuf.Empty\"\x00\x12\x34\n\x05\x42lank\x12\x11.proto.BlankLines\x1a\x16.google.protobuf.Empty\"\x00\x12-\n\x02QR\x12\r.proto.QRCode\x1a\x16.google.protobuf.Empty\"\x00\x12/\n\x03\x42\x61r\x12\x0e.proto.Barcode\x1a\x16.google.protobuf.Empty\"\x00\x42\tZ\x07.;protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_LINE = _descriptor.Descriptor(
  name='Line',
  full_name='proto.Line',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='proto.Line.line', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='font', full_name='proto.Line.font', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=83,
)


_BLANKLINES = _descriptor.Descriptor(
  name='BlankLines',
  full_name='proto.BlankLines',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='proto.BlankLines.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='font', full_name='proto.BlankLines.font', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=127,
)


_QRCODE = _descriptor.Descriptor(
  name='QRCode',
  full_name='proto.QRCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='proto.QRCode.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_size', full_name='proto.QRCode.pixel_size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='center', full_name='proto.QRCode.center', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=187,
)


_BARCODE = _descriptor.Descriptor(
  name='Barcode',
  full_name='proto.Barcode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='proto.Barcode.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='center', full_name='proto.Barcode.center', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blanks', full_name='proto.Barcode.blanks', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['Line'] = _LINE
DESCRIPTOR.message_types_by_name['BlankLines'] = _BLANKLINES
DESCRIPTOR.message_types_by_name['QRCode'] = _QRCODE
DESCRIPTOR.message_types_by_name['Barcode'] = _BARCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Line = _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), {
  'DESCRIPTOR' : _LINE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:proto.Line)
  })
_sym_db.RegisterMessage(Line)

BlankLines = _reflection.GeneratedProtocolMessageType('BlankLines', (_message.Message,), {
  'DESCRIPTOR' : _BLANKLINES,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:proto.BlankLines)
  })
_sym_db.RegisterMessage(BlankLines)

QRCode = _reflection.GeneratedProtocolMessageType('QRCode', (_message.Message,), {
  'DESCRIPTOR' : _QRCODE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:proto.QRCode)
  })
_sym_db.RegisterMessage(QRCode)

Barcode = _reflection.GeneratedProtocolMessageType('Barcode', (_message.Message,), {
  'DESCRIPTOR' : _BARCODE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:proto.Barcode)
  })
_sym_db.RegisterMessage(Barcode)


DESCRIPTOR._options = None

_PRINTSERVICE = _descriptor.ServiceDescriptor(
  name='PrintService',
  full_name='proto.PrintService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=247,
  serialized_end=459,
  methods=[
  _descriptor.MethodDescriptor(
    name='Print',
    full_name='proto.PrintService.Print',
    index=0,
    containing_service=None,
    input_type=_LINE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Blank',
    full_name='proto.PrintService.Blank',
    index=1,
    containing_service=None,
    input_type=_BLANKLINES,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QR',
    full_name='proto.PrintService.QR',
    index=2,
    containing_service=None,
    input_type=_QRCODE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Bar',
    full_name='proto.PrintService.Bar',
    index=3,
    containing_service=None,
    input_type=_BARCODE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRINTSERVICE)

DESCRIPTOR.services_by_name['PrintService'] = _PRINTSERVICE

# @@protoc_insertion_point(module_scope)
